mysqlPvc:
  storage: 8Gi

mysql:
  rootPassword: "wordpress"
  databaseName: "wordpress"
  user: "wordpress"
  password: "wordpress"

wordpressPvc:
  storage: 8Gi

wordpress:
  dbHost: wordpress-mysql
  dbName: "wordpress"
  dbUser: "wordpress"
  dbPassword: "wordpress"

virtualServer:
  host: example.org
  upstreams:
    name: wordpress
    service: wordpress
    port: 80
  routes:
    path: /
    action:
      pass: wordpress
