apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: wordpress
spec:
  host: {{ Values.virtualServer.host }}
  upstreams:
  - name: {{ Values.virtualServer.upstreams.name }}
    service: {{ Values.virtualServer.upstreams.service }}
    port: {{ Values.virtualServer.upstreams.port }}
  routes:
  - path: {{ Values.virtualServer.routes.path }}
    action:
      pass: {{ Values.virtualServer.routes.action.pass }}
