apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: wordpress
spec:
  host: {{ .Values.virtualServer.host }}
  # tls:
  #   secret: nginx-tls
  #   redirect:
  #     enable: true
  upstreams:
  - name: {{ .Values.virtualServer.upstreams.name }}
    service: {{ .Values.virtualServer.upstreams.service }}
    port: {{ .Values.virtualServer.upstreams.port }}
  routes:
  - path: {{ .Values.virtualServer.routes.path }}
    action:
      pass: {{ .Values.virtualServer.routes.action.pass }}
  - path: {{ .Values.virtualServer.routes.pathNs1 }}
    route: {{ .Values.virtualServer.routes.routeNs1 }}
  - path: {{ .Values.virtualServer.routes.pathNs2 }}
    route: {{ .Values.virtualServer.routes.routeNs2 }}
